### ISSUE TITLE
Add hardcoded country BE

### ISSUE THREAD

**Issue by JTubex** [geo6/geocoder-php-geopunt-provider#8]
I'm using this module on a Drupal website, by using https://www.drupal.org/project/geocoder and https://drupal.org/project/address.

Currently, the geocoder module reverse geocoders coordinates and retrieves the right result. But the address module isn't saving this result, since it expects a country.

So I think there are 2 solutions: 

1. Add an hardcoded country in this library
2. Update the geocoder module, to add a hardcoded country, to make this work in Drupal.

**Comment by jbelien** [comment]
See https://github.com/geo6/geocoder-php-geopunt-provider/pull/9#issuecomment-1577346733
